#!/bin/bash
source $SCRIPT_PATH/.defaults

PRIV_KEY=$1
PASS_FILE=$2
PUBL_OUT=$3


if [ "$PUBL_OUT" == "" ];then
	PUBL_OUT=$DEFAULT_PUBL_OUT
fi


if [ "$PASS_FILE" == "" ];then
	echo "Please specify password file."
elif [ "$PRIV_KEY"  ==  "" ];then
	echo "Please specify private key file."
else
	# Generating RSA Public key from retrieved RSA Private key
	openssl rsa -in $PRIV_KEY -pubout -outform PEM -out $PUBL_OUT -passin file:$PASS_FILE 
fi



