#!/bin/bash

__set-brightness(){
	if (( $(echo "$1 >= 0.0 && $1 <= 1.0" | bc -l)  ))  ;then
        	xrandr --output $2 --brightness $1
        else
        	echo "[-] Specified brightness($1) out of range."
	fi
}

PRIMARY_MONITOR=$(primary-monitor)

BRIGHTNESS=$1
MONITOR=$2


if [[ $MONITOR == "" ]];then
	MONITOR=$PRIMARY_MONITOR
fi


if [ $BRIGHTNESS == "" ];then
	echo "Usage : set-brightness <display-name> <brightness:0-1>"
else
	if [ $(list-monitors | grep "$MONITOR") ];then
		__set-brightness $BRIGHTNESS $MONITOR

	elif [ "$MONITOR" == "ALL" ];then

		for mon in $(list-monitors);
		do
			__set-brightness $BRIGHTNESS $mon
		done

	else
		echo "[-] $MONITOR not connected. Connected monitors : "
		list-monitors
		
	fi
fi

